version: "3.9"

services:

  redis:
    container_name: plea_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    container_name: plea_backend
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/app/

  celery_worker:
    build: .
    container_name: plea_celery_worker
    command: sh -c "celery -A plea worker --loglevel=info"
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app/

  smtp4dev:
    container_name: plea_smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev


volumes:
  smtp4dev-data:
